"""add knowledge base model

Revision ID: 60ea514cfc36
Revises: 0a073a23c9cd
Create Date: 2026-06-17 00:57:03.627682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '60ea514cfc36'
down_revision = '0a073a23c9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
