/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutToolsRouteImport } from './routes/_layout/tools'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPromptsRouteImport } from './routes/_layout/prompts'
import { Route as LayoutKnowledgeBasesRouteImport } from './routes/_layout/knowledge-bases'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutEvalRouteImport } from './routes/_layout/eval'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRouteImport } from './routes/_layout/knowledge-bases.$knowledgeBaseId.documents'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsRoute = LayoutToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPromptsRoute = LayoutPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBasesRoute = LayoutKnowledgeBasesRouteImport.update({
  id: '/knowledge-bases',
  path: '/knowledge-bases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEvalRoute = LayoutEvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRoute =
  LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRouteImport.update({
    id: '/$knowledgeBaseId/documents',
    path: '/$knowledgeBaseId/documents',
    getParentRoute: () => LayoutKnowledgeBasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/eval': typeof LayoutEvalRoute
  '/items': typeof LayoutItemsRoute
  '/knowledge-bases': typeof LayoutKnowledgeBasesRouteWithChildren
  '/prompts': typeof LayoutPromptsRoute
  '/settings': typeof LayoutSettingsRoute
  '/tools': typeof LayoutToolsRoute
  '/knowledge-bases/$knowledgeBaseId/documents': typeof LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/eval': typeof LayoutEvalRoute
  '/items': typeof LayoutItemsRoute
  '/knowledge-bases': typeof LayoutKnowledgeBasesRouteWithChildren
  '/prompts': typeof LayoutPromptsRoute
  '/settings': typeof LayoutSettingsRoute
  '/tools': typeof LayoutToolsRoute
  '/': typeof LayoutIndexRoute
  '/knowledge-bases/$knowledgeBaseId/documents': typeof LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/eval': typeof LayoutEvalRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/knowledge-bases': typeof LayoutKnowledgeBasesRouteWithChildren
  '/_layout/prompts': typeof LayoutPromptsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tools': typeof LayoutToolsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/knowledge-bases/$knowledgeBaseId/documents': typeof LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/eval'
    | '/items'
    | '/knowledge-bases'
    | '/prompts'
    | '/settings'
    | '/tools'
    | '/knowledge-bases/$knowledgeBaseId/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/eval'
    | '/items'
    | '/knowledge-bases'
    | '/prompts'
    | '/settings'
    | '/tools'
    | '/'
    | '/knowledge-bases/$knowledgeBaseId/documents'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/chat'
    | '/_layout/eval'
    | '/_layout/items'
    | '/_layout/knowledge-bases'
    | '/_layout/prompts'
    | '/_layout/settings'
    | '/_layout/tools'
    | '/_layout/'
    | '/_layout/knowledge-bases/$knowledgeBaseId/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools': {
      id: '/_layout/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof LayoutToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/prompts': {
      id: '/_layout/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof LayoutPromptsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-bases': {
      id: '/_layout/knowledge-bases'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases'
      preLoaderRoute: typeof LayoutKnowledgeBasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/eval': {
      id: '/_layout/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof LayoutEvalRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-bases/$knowledgeBaseId/documents': {
      id: '/_layout/knowledge-bases/$knowledgeBaseId/documents'
      path: '/$knowledgeBaseId/documents'
      fullPath: '/knowledge-bases/$knowledgeBaseId/documents'
      preLoaderRoute: typeof LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRouteImport
      parentRoute: typeof LayoutKnowledgeBasesRoute
    }
  }
}

interface LayoutKnowledgeBasesRouteChildren {
  LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRoute: typeof LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRoute
}

const LayoutKnowledgeBasesRouteChildren: LayoutKnowledgeBasesRouteChildren = {
  LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRoute:
    LayoutKnowledgeBasesKnowledgeBaseIdDocumentsRoute,
}

const LayoutKnowledgeBasesRouteWithChildren =
  LayoutKnowledgeBasesRoute._addFileChildren(LayoutKnowledgeBasesRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutEvalRoute: typeof LayoutEvalRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutKnowledgeBasesRoute: typeof LayoutKnowledgeBasesRouteWithChildren
  LayoutPromptsRoute: typeof LayoutPromptsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutToolsRoute: typeof LayoutToolsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutEvalRoute: LayoutEvalRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutKnowledgeBasesRoute: LayoutKnowledgeBasesRouteWithChildren,
  LayoutPromptsRoute: LayoutPromptsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutToolsRoute: LayoutToolsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
